npmRegistryServer: "http://10.0.10.80:4873"

# npmScopes: {
#   ctincsp: {
#     npmPublishRegistry: "http://10.0.10.80:4873",
#     npmRegistryServer: "http://10.0.10.80:4873",
#     npmAlwaysAuth: "http://10.0.10.80:4873",
#     npmAuthIdent: "http://10.0.10.80:4873",
#     npmAuthToken: "http://10.0.10.80:4873",
#   },
# },
unsafeHttpWhitelist: ["10.0.10.80"]
nodeLinker: "node-modules"